LIBS = -lm
SOURCE = ../source/
TARGET = ../target/

game:
	gcc ${SOURCE}game.c ${SOURCE}game.h ${SOURCE}strategy.c ${SOURCE}strategy.h ${SOURCE}tables.c -o ${TARGET}game ${LIBS}
clean:
	# rm -f ${TARGET}game
